### ISSUE TITLE
注册多个路由服务类 时，路由match错误问题

### ISSUE THREAD

**Issue by phatesee** [WinfredWang/express-decorator#4]
//  LoginService.ts
@Path("/login")
export class LoginService {
  @GET('/')
  loginPage(
    @Response res: any) {
  }}  
// HomeService.ts
@Path("/home")
export class HomeService {
  @GET('')
  getHomepage(
    @CookieParam("token") token: string, 
    @Response res: any) {
  }
注册多个路径，RegisterService(app, [HomeService, LoginService, UserService]); 
express服务跑成功.
打开 localhost:3000/login  进的确是home页面。

// register.ts   
export function RegisterService(app, serviceClazzes: any[]) { 
  //  let router = Router();    // router变量声明放在下面的循环体中，不会出现当前问题
    serviceClazzes.forEach(ServiceClazz => {
       let router = Router();    // ++++++++++++
        let meta = getClazz(ServiceClazz.prototype);
        let serviceInstance = new ServiceClazz();
        let routes = meta.routes;
// .....
}

**Comment by errr0l** [comment]
我也遇到这个问题了 @phatesee 在RegisterService这个函数里面, 每个服务应该独立对应一个路由才对

**Comment by phatesee** [comment]
这个模块你实际项目中用了吗
